# Generated by Django 4.0.3 on 2022-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment_active_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='automobile',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(default='5TEHN72N13Z221228', max_length=17),
            preserve_default=False,
        ),
    ]
