# Generated by Django 4.0.3 on 2022-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_serviceappointment_automobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='active',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(choices=[(0, 'ACTIVE'), (1, 'FINISHED'), (2, 'CANCELLED')], default='ACTIVE', max_length=20),
        ),
    ]
